# Look up train arrival times using the GTFS_RT custom component (https://github.com/zacs/ha-gtfs-rt).
# You need to get your own MTA API Key, and also look up the stopID of your station at: https://transitfeeds.com/p/mta/79/latest/stops

# Find subway station codes here: https://catalog.data.gov/dataset/mta-subway-stations-and-complexes

# Alternatively, you can also use the GoodService.io API:
# https://www.goodservice.io/api/stops/<stop_id>
sensor:
  ######### 7 Train  #########
  - platform: gtfs_rt
    trip_update_url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs"
    scan_interval: 60
    entity_namespace: gtfs_mta_subway
    departures:
      - name: "7 Uptown"
        route: "7"
        stopid: "723N"
      - name: "7 Downtown"
        route: "7"
        stopid: "723S"

  # Get train service status from Goodservice.io

  - platform: rest
    resource: https://www.goodservice.io/api/routes/7
    method: GET
    scan_interval: 300
    name: "MTA Subway 7 Service Status"
    value_template: "{{ value_json.status }}"
    json_attributes:
      - "color"
      - "service_change_summaries"
      - "direction_statuses"
      - "delay_summaries"
      - "service_irregularity_summaries"
      - "service_changes"

  # Calcualte time between trains
  - platform: template
    sensors:
      time_between_trains_7_uptown:
        friendly_name: "Time Between Trains: 7 Uptown"
        value_template: >
          {% set due_in = states.sensor.gtfs_mta_subway_7_uptown.attributes.get('Due in') %}
          {% set next_due_in = states.sensor.gtfs_mta_subway_7_uptown.attributes.get('Next bus due in') %}
          {{ (next_due_in - due_in) if due_in is not none and next_due_in is not none else 'unknown' }}
        unit_of_measurement: "min"

      time_between_trains_7_downtown:
        friendly_name: "Time Between Trains: 7 Downtown"
        value_template: >
          {% set due_in = states.sensor.gtfs_mta_subway_7_downtown.attributes.get('Due in') %}
          {% set next_due_in = states.sensor.gtfs_mta_subway_7_downtown.attributes.get('Next bus due in') %}
          {{ (next_due_in - due_in) if due_in is not none and next_due_in is not none else 'unknown' }}
        unit_of_measurement: "min"

  # Create some rolling averages of trains
  - platform: statistics
    name: "Time Between Trains 30-Minute Average: 7 Uptown"
    entity_id: sensor.time_between_trains_7_uptown
    state_characteristic: mean
    max_age:
      minutes: 30
    precision: 1
  - platform: statistics
    name: "Time Between Trains 30-Minute Average: 7 Downtown"
    entity_id: sensor.time_between_trains_7_downtown
    state_characteristic: mean
    max_age:
      minutes: 30
    precision: 1
  ######### 6 Train  #########
  - platform: gtfs_rt
    trip_update_url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs"
    scan_interval: 60
    entity_namespace: gtfs_mta_subway
    departures:
      - name: "6 Uptown"
        route: "6"
        stopid: "631N"
      - name: "6 Downtown"
        route: "6"
        stopid: "631S"

  # Get train service status from Goodservice.io

  - platform: rest
    resource: https://www.goodservice.io/api/routes/6
    method: GET
    scan_interval: 300
    name: "MTA Subway 6 Service Status"
    value_template: "{{ value_json.status }}"
    json_attributes:
      - "color"
      - "service_change_summaries"
      - "direction_statuses"
      - "delay_summaries"
      - "service_irregularity_summaries"
      - "service_changes"

  # Calcualte time between trains
  - platform: template
    sensors:
      time_between_trains_6_uptown:
        friendly_name: "Time Between Trains: 6 Uptown"
        value_template: >
          {% set due_in = states.sensor.gtfs_mta_subway_6_uptown.attributes.get('Due in') %}
          {% set next_due_in = states.sensor.gtfs_mta_subway_6_uptown.attributes.get('Next bus due in') %}
          {{ (next_due_in - due_in) if due_in is not none and next_due_in is not none else 'unknown' }}
        unit_of_measurement: "min"

      time_between_trains_6_downtown:
        friendly_name: "Time Between Trains: 6 Downtown"
        value_template: >
          {% set due_in = states.sensor.gtfs_mta_subway_6_downtown.attributes.get('Due in') %}
          {% set next_due_in = states.sensor.gtfs_mta_subway_6_downtown.attributes.get('Next bus due in') %}
          {{ (next_due_in - due_in) if due_in is not none and next_due_in is not none else 'unknown' }}
        unit_of_measurement: "min"
  # Create some rolling averages of trains
  - platform: statistics
    name: "Time Between Trains 30-Minute Average: 6 Uptown"
    entity_id: sensor.time_between_trains_6_uptown
    state_characteristic: mean
    max_age:
      minutes: 30
    precision: 1
  - platform: statistics
    name: "Time Between Trains 30-Minute Average: 6 Downtown"
    entity_id: sensor.time_between_trains_6_downtown
    state_characteristic: mean
    max_age:
      minutes: 30
    precision: 1
  ######### E Train  #########
  - platform: gtfs_rt
    trip_update_url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace"
    scan_interval: 60
    entity_namespace: gtfs_mta_subway
    departures:
      - name: "E Uptown"
        route: "E"
        stopid: "F11N"
      - name: "E Downtown"
        route: "E"
        stopid: "F11S"

  # Get train service status from Goodservice.io

  - platform: rest
    resource: https://www.goodservice.io/api/routes/E
    method: GET
    scan_interval: 300
    name: "MTA Subway E Service Status"
    value_template: "{{ value_json.status }}"
    json_attributes:
      - "color"
      - "service_change_summaries"
      - "direction_statuses"
      - "delay_summaries"
      - "service_irregularity_summaries"
      - "service_changes"

  # Calcualte time between trains
  - platform: template
    sensors:
      time_between_trains_e_uptown:
        friendly_name: "Time Between Trains: E Uptown"
        value_template: >
          {% set due_in = states.sensor.gtfs_mta_subway_e_uptown.attributes.get('Due in') %}
          {% set next_due_in = states.sensor.gtfs_mta_subway_e_uptown.attributes.get('Next bus due in') %}
          {{ (next_due_in - due_in) if due_in is not none and next_due_in is not none else 'unknown' }}
        unit_of_measurement: "min"

      time_between_trains_e_downtown:
        friendly_name: "Time Between Trains: E Downtown"
        value_template: >
          {% set due_in = states.sensor.gtfs_mta_subway_e_downtown.attributes.get('Due in') %}
          {% set next_due_in = states.sensor.gtfs_mta_subway_e_downtown.attributes.get('Next bus due in') %}
          {{ (next_due_in - due_in) if due_in is not none and next_due_in is not none else 'unknown' }}
        unit_of_measurement: "min"

      current_weather_condition:
        friendly_name: "Current Weather Condition"
        value_template: >
          {% if is_state('sun.sun', 'above_horizon') %}
            {{ states('sensor.home_condition_day_0') }}
          {% else %}
            {{ states('sensor.home_condition_night_0') }}
          {% endif %}

  # Create some rolling averages of trains
  - platform: statistics
    name: "Time Between Trains 30-Minute Average: E Uptown"
    entity_id: sensor.time_between_trains_e_uptown
    state_characteristic: mean
    max_age:
      minutes: 30
    precision: 1
  - platform: statistics
    name: "Time Between Trains 30-Minute Average: E Downtown"
    entity_id: sensor.time_between_trains_e_downtown
    state_characteristic: mean
    max_age:
      minutes: 30
    precision: 1

template:
  # Update screen only when occupancy is detected.

  - binary_sensor:
      - name: Weatherman Motion Detected
        unique_id: "dfa78de7-d761-425f-9731-86f1af332eac"
        device_class: "occupancy"
        delay_off: 00:01
        state: >-
          {%- if states('binary_sensor.bedroom_is_occupied') == 'on' and
                 states('binary_sensor.everyone_at_home_is_asleep') == 'off' %}
            on
          {%- else -%}
            off
          {%- endif -%}
  # - sensor:
  #     - name: "Time Between Trains: 7 Downtown"
  #       state: >
  #         {% set due_in = states.sensor.gtfs_mta_subway_7_downtown.attributes['Due in'] %}
  #         {% set next_due_in = states.sensor.gtfs_mta_subway_7_downtown.attributes['Next bus due in'] %}
  #         {{ next_due_in - due_in if due_in is not none and next_due_in is not none else 'unknown' }}
  #       unit_of_measurement: "min"
  # - sensor:
  #     - name: "Time Between Trains: 7 Uptown"
  #       state: >
  #         {% set due_in = states.sensor.gtfs_mta_subway_7_uptown.attributes['Due in'] %}
  #         {% set next_due_in = states.sensor.gtfs_mta_subway_7_uptown.attributes['Next bus due in'] %}
  #         {{ next_due_in - due_in if due_in is not none and next_due_in is not none else 'unknown' }}
  #       unit_of_measurement: "min"

  # Bundle up all the data to send over to Weatherman (ESPHome device).

  - trigger:
      platform: time_pattern
      minutes: "/1"
    action:
      - service: weather.get_forecasts
        target:
          entity_id: weather.forecast_home
        data:
          type: hourly
        response_variable: hourly
    sensor:
      - name: Weatherman Data
        state: "OK"
        attributes:
          # train_status_7: >
          #   {{ states('sensor.mta_subway_7_service_status') | upper }}
          train_status_6_uptown: >
            {{ state_attr('sensor.mta_subway_6_service_status', 'direction_statuses').north | upper }}
          train_status_6_downtown: >
            {{ state_attr('sensor.mta_subway_6_service_status', 'direction_statuses').south | upper }}
          train_status_7_uptown: >
            {{ state_attr('sensor.mta_subway_7_service_status', 'direction_statuses').north | upper }}
          train_status_7_downtown: >
            {{ state_attr('sensor.mta_subway_7_service_status', 'direction_statuses').south | upper }}
          train_status_e_uptown: >
            {{ state_attr('sensor.mta_subway_e_service_status', 'direction_statuses').north | upper }}
          train_status_e_downtown: >
            {{ state_attr('sensor.mta_subway_e_service_status', 'direction_statuses').south | upper }}
          weather_condition_now: >
            {% set cond_now = states('weather.forecast_home') %}
            {% if states('sun.sun') == 'below_horizon' %}
                {% if cond_now == 'sunny' %} night {% elif cond_now == 'partlycloudy' %} night-partly-cloudy {% else %} {{ cond_now }} {% endif %}
            {% else %}
                {{ cond_now }}
            {% endif %}

          weather_condition_0: >
            {% set cond0 = hourly['weather.forecast_home'].forecast[0].condition %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond0_time = as_timestamp(hourly['weather.forecast_home'].forecast[0].datetime) %}
            {% if cond0_time > next_setting or cond0_time < next_rising < next_setting %}
                {% if cond0 == 'sunny' %} night {% elif cond0 == 'partlycloudy' %} night-partly-cloudy {% else %} {{ cond0 }} {% endif %}
            {% else %}
                {{ cond0 }}
            {% endif %}
          weather_temperature_0: >
            {{ hourly['weather.forecast_home'].forecast[0].temperature | round }}
          weather_timestamp_0: >
            {{ as_timestamp(hourly['weather.forecast_home'].forecast[0].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(hourly['weather.forecast_home'].forecast[0].datetime) | timestamp_custom('%p') }}

          weather_condition_1: >
            {% set cond1 = hourly['weather.forecast_home'].forecast[1].condition %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond1_time = as_timestamp(hourly['weather.forecast_home'].forecast[1].datetime) %}
            {% if cond1_time > next_setting or cond1_time < next_rising < next_setting %}
                {% if cond1 == 'sunny' %} night {% elif cond1 == 'partlycloudy' %} night-partly-cloudy {% else %} {{ cond1 }} {% endif %}
            {% else %}
                {{ cond1 }}
            {% endif %}
          weather_temperature_1: >
            {{ hourly['weather.forecast_home'].forecast[1].temperature | round }}
          weather_timestamp_1: >
            {{ as_timestamp(hourly['weather.forecast_home'].forecast[1].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(hourly['weather.forecast_home'].forecast[1].datetime) | timestamp_custom('%p') }}

          weather_condition_2: >
            {% set cond2 = hourly['weather.forecast_home'].forecast[2].condition %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond2_time = as_timestamp(hourly['weather.forecast_home'].forecast[2].datetime) %}
            {% if cond2_time > next_setting or cond2_time < next_rising < next_setting %}
                {% if cond2 == 'sunny' %} night {% elif cond2 == 'partlycloudy' %} night-partly-cloudy {% else %} {{ cond2 }} {% endif %}
            {% else %}
                {{ cond2 }}
            {% endif %}
          weather_temperature_2: >
            {{ hourly['weather.forecast_home'].forecast[2].temperature | round }}
          weather_timestamp_2: >
            {{ as_timestamp(hourly['weather.forecast_home'].forecast[2].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(hourly['weather.forecast_home'].forecast[2].datetime) | timestamp_custom('%p') }}

          weather_condition_3: >
            {% set cond3 = hourly['weather.forecast_home'].forecast[3].condition %}
            {% set next_setting = as_timestamp(state_attr('sun.sun', 'next_setting')) %}
            {% set next_rising = as_timestamp(state_attr('sun.sun', 'next_rising')) %}
            {% set cond3_time = as_timestamp(hourly['weather.forecast_home'].forecast[3].datetime) %}
            {% if cond3_time > next_setting or cond3_time < next_rising < next_setting %}
                {% if cond3 == 'sunny' %} night {% elif cond3 == 'partlycloudy' %} night-partly-cloudy {% else %} {{ cond3 }} {% endif %}
            {% else %}
                {{ cond3 }}
            {% endif %}
          weather_temperature_3: >
            {{ hourly['weather.forecast_home'].forecast[3].temperature | round }}
          weather_timestamp_3: >
            {{ as_timestamp(hourly['weather.forecast_home'].forecast[3].datetime) | timestamp_custom('%I') | int }} {{ as_timestamp(hourly['weather.forecast_home'].forecast[3].datetime) | timestamp_custom('%p') }}
